// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhjSuGEuOOrdrfYmwnTVaiNKrwBNV5jc',
    appId: '1:1084908102787:web:07335066790c06aa75e7b6',
    messagingSenderId: '1084908102787',
    projectId: 'brewsypos',
    authDomain: 'brewsypos.firebaseapp.com',
    storageBucket: 'brewsypos.firebasestorage.app',
    measurementId: 'G-21V3L0PS57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKaX3rX5LGKepoZKaMbFYJkOtrrQiHNeo',
    appId: '1:1084908102787:android:8619967957ec3aad75e7b6',
    messagingSenderId: '1084908102787',
    projectId: 'brewsypos',
    storageBucket: 'brewsypos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_WQoEB_JEYnyhX94TMPiQzZcJMhe_hSg',
    appId: '1:1084908102787:ios:18074f294b45b9fe75e7b6',
    messagingSenderId: '1084908102787',
    projectId: 'brewsypos',
    storageBucket: 'brewsypos.firebasestorage.app',
    iosBundleId: 'com.example.brewsyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_WQoEB_JEYnyhX94TMPiQzZcJMhe_hSg',
    appId: '1:1084908102787:ios:18074f294b45b9fe75e7b6',
    messagingSenderId: '1084908102787',
    projectId: 'brewsypos',
    storageBucket: 'brewsypos.firebasestorage.app',
    iosBundleId: 'com.example.brewsyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7UQdpMsT37vHpHoPKEErS7HFPQW6zHKk',
    appId: '1:1084908102787:web:fda2fd9c4594811275e7b6',
    messagingSenderId: '1084908102787',
    projectId: 'brewsypos',
    authDomain: 'brewsypos.firebaseapp.com',
    storageBucket: 'brewsypos.firebasestorage.app',
    measurementId: 'G-6DKB4QPSCL',
  );
}
